### ISSUE TITLE
🚀 Update Roadmap

### ISSUE THREAD

**Issue by rphl** [rphl/corona-widget#69]
**Grobe Roadmap fürs nächste Update:**
Kommentare bitte im jeweiligen Ticket. Fehlt was? Ticket ;-)

_Durchgestriche Tickets sind fertig. Können, müssen aber nicht im Develop Branch verfügbar sein. 
Develop kann, muss aber nicht defekt sein. Also Vorsicht ;-)_

* [x] ~~Code refactoring~~
* [x] ~~AutoUpdate (Install) Funktion / Selfupdate #24~~
* [x] ~~Split Cache Files into Local/State/Country~~
* [x] ~~Abruf Historischer Daten via Api + Caching #66~~
* [x] ~~Location Caching für Widget ohne Parameter #64~~
* [x] ~~MediumWidget doppelte BL Daten ersetzten... #26~~
